### ISSUE TITLE
Device Type: Clone on first-party controller.

### ISSUE THREAD

**Issue by e3ndr** [dualshock-tools/dualshock-tools.github.io#12]
Title. Is there any way for me to get you some debug data?

![opera_KbIe5rQaGu](https://github.com/dualshock-tools/dualshock-tools.github.io/assets/33337309/25983192-b723-4f1c-9599-53115035623e)

I have a ["Glacier White"](https://a.co/d/6SwaUq4) controller.

**Comment by Excrubulent** [comment]
Having the same issue.  I bought two original controllers from a reputable big box store in Australia years ago.  I have a very hard time imagining how they could've been clones in any way.  They're labelled as Sony products and I really doubt they're knock-offs.

**Comment by preston176** [comment]
same issue yet im having original controller old one from 2015

**Comment by NanoPi** [comment]
Were any of you using a Bluetooth connection at the time?

Using a Bluetooth connection is how I get the clone message on an original controller.
I don't get the clone message when the controller is connected by USB. Have done stick calibration over USB several weeks ago. (JDM-055, FW from 2017)

On Bluetooth, [device.receiveFeatureReport(0x81) on line 112](https://github.com/dualshock-tools/dualshock-tools.github.io/blob/20075c4552f70bc0b8aa296ca12efe531d263788/core.js#L112) results in running the catch block with e containing "Failed to receive the feature report".

**Comment by e3ndr** [comment]
> Were any of you using a Bluetooth connection at the time?
> 
> 
> 
> Using a Bluetooth connection is how I get the clone message on an original controller.
> 
> I don't get the clone message when the controller is connected by USB. Have done stick calibration over USB several weeks ago. (JDM-055, FW from 2017)
> 
> 
> 
> On Bluetooth, [device.receiveFeatureReport(0x81) on line 112](https://github.com/dualshock-tools/dualshock-tools.github.io/blob/20075c4552f70bc0b8aa296ca12efe531d263788/core.js#L112) results in running the catch block with e containing "Failed to receive the feature report".

I was, yeah. Does the web tool work over USB or would I need to use the Python version?

**Comment by NanoPi** [comment]
> I was, yeah. Does the web tool work over USB or would I need to use the Python version?

Web version worked for me over USB. Chromium, Windows 10.

**Comment by Excrubulent** [comment]
Okay, doing that worked for me, thanks so much.  It might be an idea to add this solution to the error message.

**Comment by Doyle4** [comment]
When using USB it uses the data lines to connect to the controller board which is what allows it be flashed etc.
Using bluetooth will show connected but not have access to write to the section thats needed.
Although it says clone, pretty good that its stops anything from been flashed as it could cause issues or even brick the controller.

**Comment by dualshock-tools** [comment]
With the latest version, the website should warn if the controller is connected via Bluetooth instead of USB. Let me know if that works!

**Comment by e3ndr** [comment]
Can confirm that using USB fixed the issue for me! Thanks for the hard work @dualshock-tools. I'll check the bluetooth warning in a couple of days. Feel free to close this :)
