### ISSUE TITLE
Will there be a deadzone calibration tool?

### ISSUE THREAD

**Issue by JuanchoGYT** [dualshock-tools/dualshock-tools.github.io#15]
Stick drift is becoming an issue on dualsense controllers, specially BDM-010 and 020 models, and a friend an i are getting tired of having to replace the stick modules themselves, just to have the same client bring back the exact same controller with the exact same issue, we gave him hall effect stick modules and now the center point is inconsistent and even after recentering the sticks and writing permanently the changes, center point is still inconsistent after recalibration. This is not the only 1st to 2ng gen dualsense controllers we've had to do this, there were lots of dualsense controllers we've had to fix because of stick drift that we're just about to give up and tell our customers to just buy a new controller and check that it is at least a 3rd gen dualsense.

**Comment by dotdissent** [comment]
You're finding that the Alps mech is the problem and not the potentiometers? Have you tried installing new 2.3k pots on the affected axis and then performing both center and range calibration? This has worked for me on every Dualsense at my shop, I've yet to see one with an actually damaged mech so I'm surprised you're getting them so often.

**Comment by JuanchoGYT** [comment]
We've tried that, and on a used Dualsense controller i bought for myself (which is one of the many BDM-010 units we had to repair) and after noticing the stick drift on the Y axis in the right stick i decided to check the potentiometer, there was an actual hair inside of it that gave it an irrepairable damage, don't know how did a hair got stuck inside the potentiometer but it did damage the thing and we're yet to receive our hall effect joysticks, so a deadzone adjustment tool in the calibration tools would be very convenient for those who are waiting for their replacement joystick modules to arrive.

**Comment by dualshock-tools** [comment]
Nope, the website can only start/stop calibration, without any extra setting (e.g. deadzone).
