### ISSUE TITLE
feature request - calibrate stick range

### ISSUE THREAD

**Issue by michaelhongsam** [dualshock-tools/dualshock-tools.github.io#19]
I think it would be helpful to have an offset that a user could specify to tighten or loosen the range for the stick range calibration.

This is because sometimes the plastic ring around the sticks can bend under pressure while rotating the sticks. Which leads to the maximum range to be larger than intended.

**Comment by dualshock-tools** [comment]
Hi, this cannot be implemented as the calibration algorithm is in the controller firmware. The website can only start/stop the calibration.
