### ISSUE TITLE
How can i revert the changes made to my ps5 controller?

### ISSUE THREAD

**Issue by vendxtta** [dualshock-tools/dualshock-tools.github.io#21]
I did click the apply permanant changes button and i want to undo it but i dont know how and its really getting on my nerves.
Please help I would just like to revert it to its factory original settings.
Thanks!

**Comment by ggsudgg5** [comment]
I did click the apply permanant changes button and i want to undo it but i dont know how to
Please help I would just like to revert it to its factory original settings.
