### ISSUE TITLE
Controller Accidentally Flashed to 100% on both sticks

### ISSUE THREAD

**Issue by rafpao** [dualshock-tools/dualshock-tools.github.io#24]
Unfortunately my sticks were both accidentally flashed to 100% for all corners (as in I can push both to a corner and they respond). Is there anyway for me to reflash the centers or the whole controller firmware or is my controller just bricked. If anyone can help me thank you so much!

https://github.com/user-attachments/assets/ee60d0f7-bc53-460b-b0d8-3004ba1dae80

**Comment by dualshock-tools** [comment]
Do again range calibration and then center calibration, it should solve the problem
