### ISSUE TITLE
BDM-050 detection.

### ISSUE THREAD

**Issue by surgiie** [dualshock-tools/dualshock-tools.github.io#26]
Newest board model is not detectable: 

![image](https://github.com/user-attachments/assets/10146511-f7d5-497d-8660-9e525c207789)

**Comment by dualshock-tools** [comment]
hi, thanks for the firmware info. it should be fixed now, let me know if it works

**Comment by surgiie** [comment]
@dualshock-tools Yep can confirm it is fixed.
