### ISSUE TITLE
Offer of a DualSense Edge controller

### ISSUE THREAD

**Issue by Qard** [dualshock-tools/dualshock-tools.github.io#27]
Hi there, I'd really love to have DualSense Edge supported by this tool. I don't have the time to poke at it myself and figure out how to get it working, but if you'd like (@dualshock-tools), I'm happy to buy one for you if you provide an amazon wishlist or something like that where I can buy it for you. Otherwise, you can reach out to me through the contact info in my profile and we can figure something out. 🙂

**Comment by dualshock-tools** [comment]
Hi, thank you for your offer! I already have a DS Edge and I'm currently working on it. Unfortunately it's taking longer than expected. If you want to be updated about it, join our discord server by clicking on the discord icon on the website.
