### ISSUE TITLE
THIS TOOL BREAKS CONTROLLER - AVOID USING IT

### ISSUE THREAD

**Issue by hextrim** [dualshock-tools/dualshock-tools.github.io#40]
Hi,

This tool broke my sticks calibration and both are now set at -/+ 1.0 constantly.

There is now way to revert this change.

I just lost SCUF Dual Sense worth 250£/$ - what a piece of crap this software is.

Regards,
W

**Comment by KonzolozZ** [comment]
Follow Calibration Instructions and Calibrate Your Controller THEN STORE DATA.

**Comment by hextrim** [comment]
I did this several times after the first calibration broke it
Did this on diff PC, in incognito mode, every time I plug controller in all positions starts with 1.0+/-, even during calibration process.

The worst part is that there is no way to reflash the firmware to revert that change.

My only hope is that I have to wait for PS to release new firmware, then connect controller to console and let it overwrite  maybe that will help.

**Comment by jetuaime81** [comment]
> I did this several times after the first calibration broke it Did this on diff PC, in incognito mode, every time I plug controller in all positions starts with 1.0+/-, even during calibration process.
> 
> The worst part is that there is no way to reflash the firmware to revert that change.
> 
> My only hope is that I have to wait for PS to release new firmware, then connect controller to console and let it overwrite maybe that will help.

I think this software supports only official sony dualshock 4 and dualsense controllers. SCUF is 3rd party right.

**Comment by herovaxy** [comment]
It works fine with my Dualsense BDM-010 controller. No modded things. Just plain old original controller.

**Comment by dualshock-tools** [comment]
Hi @hextrim, this seems the issue where you pressed "range calibration" and right after clicked "ok" without moving the sticks, try to do again the range calibration while rotating the sticks all around. 
If that doesn't work, there is a #help-desk channel on discord (link on the webpage) where more people can help you with that.

**Comment by simaomeyrer** [comment]
@hextrim , this is a free cost software, someone has spend much time and effort on this, it's ever good to follow good practices of comment/sugestions and issues (this topic is not a issue).
The aplication has no ads and again, is free.
As also mentioned, if you need help, there are a channel on discord to support you, with education.
